@MinimalApiProject_HostAddress = http://localhost:5266

PUT {{MinimalApiProject_HostAddress}}/

###

GET {{MinimalApiProject_HostAddress}}/

###

PATCH {{MinimalApiProject_HostAddress}}/

###

DELETE {{MinimalApiProject_HostAddress}}/

###
